### ISSUE TITLE
is dataset synthetically generated or real from a source

### ISSUE THREAD

**Issue by jbsec** [jlopez873/Telecom_Revenue_Time_Series_Forecasting#1]
sorry to just barge in here with an issue req: I work on telco data for my research and I'm just wondering where you acquired this data or if it is generated yourself, if it is generated yourself, are you able to disclose with us the underlying code/logic used to create the seasonality of the data.

no problems if not, have a good day.

**Comment by jlopez873** [comment]
Hi James,

The dataset is synthetically generated by an educational institution, unfortunately I don't have insight into how they created the seasonality in the data. The raw data is stored in the _teleco_time_series.csv_ file of this repository if you wish to use it.
